name: gen_coap_service_toc
on:
  push:
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: gen_coap_service_toc
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
